site_name: Learn Dyalog APL
site_description: The definitive Dyalog APL reference.
docs_dir: docs/
theme:
  name: material
  favicon: 'img/favicon.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.instant
  custom_dir: overrides
extra_css:
  - style/main.css
  - style/quickstart.css
extra_javascript:
  - js/announce.js