site_name: Dyalog Tutorials
site_description: How-to guides for Dyalog APL
docs_dir: docs/
repo_name: 'rikedyp/DyalogTutorials'
repo_url: 'https://github.com/rikedyp/DyalogTutorials'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
extra_css:
  - style/main.css
  - style/quickstart.css
