site_name: Tutorials
site_description: How-to guides for Dyalog APL
docs_dir: docs/
repo_name: 'rikedyp/DyalogTutorials'
repo_url: 'https://github.com/rikedyp/DyalogTutorials'
theme:
  name: material
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.instant
  custom_dir: overrides
extra_css:
  - style/main.css
  - style/quickstart.css