site_name: Developer Center
site_description: The definitive Dyalog APL reference.
docs_dir: docs/
theme:
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  name: material
  favicon: 'img/favicon.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  plugins:
    - search:
        lang: en
  custom_dir: overrides
extra_css:
  - style/main.css
  - style/quickstart.css
extra_javascript:
  - js/announce.js
nav:
  - index.md
  - Learn Dyalog APL:
    - learn-dyalog-apl/index.md
    - Getting Started:
      - getting-started/index.md
      - Typing APL Symbols: getting-started/type-apl-symbols.md
      - Name Classes: getting-started/name-classes.md
      - Functions and Operators: getting-started/functions-and-operators.md
      - Saving Your Work: getting-started/saving-your-work.md
    - learn-dyalog-apl/mastering-dyalog-apl.md 
  - APL Language:
    - apl-language/index.md
  - Tools:
    - tools/index.md
  - Interfaces:
    - interfaces/index.md
  - tips.md