site_name: Learn Dyalog APL
site_description: The definitive Dyalog APL reference.
docs_dir: docs/
repo_name: 'hashslingrz/learn-dyalog'
repo_url: 'https://github.com/hashslingrz/learn-dyalog'
theme:
  name: material
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.instant
  custom_dir: overrides
extra_css:
  - style/main.css
  - style/quickstart.css